# Generated by Django 4.0.3 on 2022-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='imgLink',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
