# Generated by Django 4.0.3 on 2022-04-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_catid_product_imglink_product_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imgLink',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
