# Generated by Django 4.0.3 on 2022-04-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_catid_remove_product_imglink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
